clients:
  google-chrome-beta: chrome
  jetbrains-(.*):
    icon: terminal
    extra: "{0}"
  firefox: firefox
  thunar: folder-open
  vlc: vlc
  signal: comment
  code-oss: code
  vesktop: 
  foot: terminal
  vscodium: code
  vmware: server
  obsidian: 
  cider: music
deliminator: " "
default_icon: dot-circle
default:
  new_desktop: true
